include:
  - board: nice_nano_v2
    shield: dac_man_5x6_left
    cmake-args: -DSHIELD_ROOT=$GITHUB_WORKSPACE/config
  - board: nice_nano_v2
    shield: dac_man_5x6_right
    cmake-args: -DSHIELD_ROOT=$GITHUB_WORKSPACE/config
